#!/usr/bin/env bats

load helpers/mock_env

# Tests for nginx config content generated by the host script

setup() {
    setup_mock_larasail
    export CONFIG_FILE="$BATS_TMPDIR/nginx_test.conf"
}

teardown() {
    rm -f "$CONFIG_FILE"
}

generate_nginx_config() {
    local domain="$1"
    local rootPath="$2"
    local phpVersion="$3"
    local serverName="$domain"

    cat > "$CONFIG_FILE" << EOF
server {

        root $rootPath/public;

        index index.php index.html index.htm;

        server_name $serverName;

        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-Content-Type-Options "nosniff";
        add_header X-XSS-Protection "1; mode=block";
        add_header Referrer-Policy "strict-origin-when-cross-origin";

        location / {
                try_files \$uri \$uri/ /index.php?\$query_string;
        }

        location ~*  \.(jpg|jpeg|png|gif)\$ {
                expires 365d;
        }

        location ~*  \.(ico|css|js)\$ {
                expires 365d;
        }

        location ~ \.php\$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/run/php/php${phpVersion}-fpm.sock;
        }

        location ~ /\.ht {
                deny all;
        }

}
EOF
}

@test "nginx config sets correct server_name" {
    generate_nginx_config "example.com" "/var/www/example" "8.5"
    grep -q "server_name example.com;" "$CONFIG_FILE"
}

@test "nginx config sets correct document root" {
    generate_nginx_config "example.com" "/var/www/example" "8.5"
    grep -q "root /var/www/example/public;" "$CONFIG_FILE"
}

@test "nginx config uses correct PHP-FPM socket" {
    generate_nginx_config "example.com" "/var/www/example" "8.5"
    grep -q "fastcgi_pass unix:/run/php/php8.5-fpm.sock;" "$CONFIG_FILE"
}

@test "nginx config contains X-Frame-Options header" {
    generate_nginx_config "example.com" "/var/www/example" "8.5"
    grep -q "X-Frame-Options" "$CONFIG_FILE"
}

@test "nginx config contains X-Content-Type-Options header" {
    generate_nginx_config "example.com" "/var/www/example" "8.5"
    grep -q "X-Content-Type-Options" "$CONFIG_FILE"
}

@test "nginx config contains X-XSS-Protection header" {
    generate_nginx_config "example.com" "/var/www/example" "8.5"
    grep -q "X-XSS-Protection" "$CONFIG_FILE"
}

@test "nginx config contains Referrer-Policy header" {
    generate_nginx_config "example.com" "/var/www/example" "8.5"
    grep -q "Referrer-Policy" "$CONFIG_FILE"
}

@test "nginx config denies .ht files" {
    generate_nginx_config "example.com" "/var/www/example" "8.5"
    grep -q "location ~ /\\\\.ht" "$CONFIG_FILE"
    grep -q "deny all;" "$CONFIG_FILE"
}

@test "nginx config has no trailing dollar-one regex bug" {
    generate_nginx_config "example.com" "/var/www/example" "8.5"
    run grep '\$1' "$CONFIG_FILE"
    [ "$status" -ne 0 ]
}

@test "nginx config PHP-FPM socket uses PHP 8.4 correctly" {
    generate_nginx_config "example.com" "/var/www/example" "8.4"
    grep -q "fastcgi_pass unix:/run/php/php8.4-fpm.sock;" "$CONFIG_FILE"
}
