#!/bin/bash

#/
#--------------------------------------------------------------------------
# Larasail Update
#--------------------------------------------------------------------------
#
# Re-downloads and installs the latest version of LaraSail.
#
#/

. /etc/.larasail/includes/colors
. /etc/.larasail/includes/format

setsail

bar
cyan "| Updating LaraSail "
bar

curl -sL https://larasail.com/install | bash
